application: umichseed
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: seed_api.APPLICATION
- url: /cron/fetch
  script: fetch.APPLICATION
  login: admin
- url: /cron/train
  script: train.APPLICATION
  login: admin

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0